# Rime dictionary
# encoding: utf-8
#
#
# jpu <pujunyu@gmail.com>
#
# éƒ¨ç½²ä½ç½®ï¼š
# ~/.config/ibus/rime  (Linux)
# ~/Library/Rime  (Mac OS)
# %APPDATA%\Rime  (Windows)
# 
# æ–¼é‡æ–°éƒ¨ç½²å¾Œç”Ÿæ•ˆ
# 
# éœ€å¢åŠ luna_pinyin.custom.yamlæ–‡ä»¶
# å…·ä½“ç¤ºä¾‹ï¼šhttps://gist.github.com/lotem/5443073
# patch:
#  translator/dictionary: luna_pinyin.emoji

---
name: luna_pinyin.emoji
version: "2015.05.17"
sort: by_weight
use_preset_vocabulary: true
# å¾ luna_pinyin.dict.yaml å°å…¥åŒ…å«å–®å­—çš„ç¢¼è¡¨
import_tables:
  - luna_pinyin
...
ğŸ˜	ai ni	1000
ğŸ˜˜	ai ni	1000
ğŸ’—	ai xin	1000
ğŸ’†	an mo	1000
ğŸ‘‹	bai bai	1000
ğŸ™	bai tuo	1000
ğŸ¢	ban gong lou	1000
ğŸš¼	bao bao	1000
ğŸ‘¶	bao bao	1000
ğŸ§	bao bing	1000
ğŸš	bei ke	1000
ğŸ˜­	bei shang	1000
ğŸ˜¢	bei shang	1000
ğŸ‘ƒ	bi	1000
ğŸ†š	bi	1000
ğŸ˜’	bi shi	1000
ğŸ‘	bi shi	1000
ğŸ˜	bi yan	1000
ğŸ“	bi ye	1000
ğŸ‘ƒ	bi zi	1000
ğŸ˜ 	bi zui	1000
ğŸª	bian li dian	1000
ğŸª	bian li shang dian	1000
ğŸ˜£	bu yao	1000
ğŸ˜·	bing	1000
ğŸ˜˜	ai ni	1000
ğŸ˜Š	kai xin	1000
ğŸ˜	xi huan	1000
ğŸ˜	bu kai xin	1000
ğŸ˜¡	sheng qi	1000
ğŸ˜²	biao qing	1000
ğŸ˜‚	ku xiao	1000
ğŸ˜“	da ji	1000
ğŸ˜–	e xin	1000
ğŸ˜ª	ai	1000
ğŸ˜œ	gui lian	1000
ğŸ˜­	biao qing	1000
ğŸ˜°	biao qing	1000
ğŸ˜¢	biao qing	1000
ğŸ˜ƒ	kai xin	1000
ğŸ˜”	kun	1000
ğŸ˜¥	biao qing	1000
ğŸ˜¨	bing	1000
ğŸ˜‰	ok	1000
ğŸ˜š	qin qin	1000
ğŸ˜	biao qing	1000
ğŸ˜Œ	mei wen ti	1000
ğŸ˜	he he	1000
ğŸ˜ 	shen qi	1000
ğŸ˜	biao qing	1000
ğŸ˜’	biao qing	1000
ğŸ˜±	shen me	1000
ğŸ˜„	biao qing	1000
ğŸ†	biao zhi	1000
ğŸš¹	biao zhi	1000
âš¡	biao zhi	1000
ğŸ…±	biao zhi	1000
ğŸšº	biao zhi	1000
ğŸš¾	biao zhi	1000
ğŸ”	biao zhi	1000
â¿	biao zhi	1000
ğŸš¬	biao zhi	1000
ğŸš»	biao zhi	1000
ğŸ…¾	biao zhi	1000
ğŸš­	biao zhi	1000
ğŸ…°	biao zhi	1000
ğŸš¼	biao zhi	1000
ğŸ…¿	biao zhi	1000
ğŸ¦	bing ji lin	1000
ğŸ¦	bing qi lin	1000
ğŸŒŠ	bo lang	1000
ğŸ˜ 	bu gao xing	1000
ğŸ˜’	bu gao xing	1000
ğŸŒˆ	cai hong	1000
ğŸ¹	cang shu	1000
ğŸ“	cao mei	1000
ğŸš¾	ce suo	1000
ğŸš½	ce suo	1000
â˜•	cha	1000
ğŸ˜	chao nong	1000
ğŸ‘•	t xu	1000
ğŸ’¤	shui	1000
ğŸ˜”	chen si	1000
ğŸ°	cheng bao	1000
ğŸ¯	cheng bao	1000
ğŸŠ	cheng zi	1000
ğŸ˜²	chi jing	1000
ğŸ˜±	chi jing	1000
ğŸ’Š	chi yao	1000
ğŸ„	chong lang	1000
ğŸ›	chong zi	1000
ğŸš½	chou shui ma tong	1000
ğŸš¢	chu an	1000
ğŸš•	chu zu che	1000
ğŸš¢	chuan	1000
ğŸ“ 	chuan zhen ji	1000
ğŸ”¨	chui zi	1000
ğŸ’©	da bian	1000
ğŸ˜­	da ku	1000
ğŸ“£	da la ba	1000
ğŸ˜	da xiang	1000
ğŸ˜‚	da xiao	1000
ğŸˆ¹	da zhe	1000
ğŸ’‰	da zhen	1000
ğŸš²	dan che	1000
ğŸ‚	dan gao	1000
ğŸ°	dan gao	1000
ğŸ˜“	dan xin	1000
ğŸ´	dao cha	1000
ğŸŒ¾	dao sui	1000
ğŸš‡	di tie	1000
ğŸšƒ	dian che	1000
ğŸ’¡	dian deng pao	1000
â˜	dian hua	1000
ğŸ’»	dian nao	1000
ğŸ“º	dian shi	1000
ğŸ“º	dian shi ji	1000
ğŸ¬	dian ying	1000
ğŸ¦	dian ying yuan	1000
ğŸ†™	ding	1000
ğŸ›	dong wu	1000
ğŸ˜	dong wu	1000
ğŸ»	dong wu	1000
ğŸ’	dong wu	1000
ğŸ¸	dong wu	1000
ğŸµ	dong wu	1000
ğŸ¯	dong wu	1000
ğŸ¬	dong wu	1000
ğŸ¦	dong wu	1000
ğŸ 	dong wu	1000
ğŸš	dong wu	1000
ğŸ—	dong wu	1000
ğŸ”	dong wu	1000
ğŸº	dong wu	1000
ğŸ·	dong wu	1000
ğŸ´	dong wu	1000
ğŸ‘	dong wu	1000
ğŸ	dong wu	1000
ğŸ±	dong wu	1000
ğŸ®	dong wu	1000
ğŸ«	dong wu	1000
ğŸ¨	dong wu	1000
ğŸŸ	dong wu	1000
ğŸ™	dong wu	1000
ğŸ¹	dong wu	1000
ğŸ¶	dong wu	1000
ğŸ	dong wu	1000
ğŸ³	dong wu	1000
ğŸ°	dong wu	1000
ğŸ­	dong wu	1000
ğŸ§	dong wu	1000
ğŸ¤	dong wu	1000
ğŸ†š	dui bi	1000
â˜	duo yun	1000
ğŸ‘¿	e mo	1000
ğŸ‘‚	er	1000
ğŸ‘‚	er duo	1000
ğŸ§	er ji	1000
ğŸ’ˆ	fa lang	1000
â›µ	fan chuan	1000
ğŸ…	fan qie	1000
ğŸ™	fan tuan	1000
âœˆ	fei ji	1000
ğŸ	feng ling	1000
ğŸ	feng ye	1000
ğŸ’‘	fu fu	1000
ğŸ”°	fu hao	1000
ã€½	fu hao	1000
ğŸˆµ	fu hao	1000
ãŠ—	fu hao	1000
âœ´	fu hao	1000
â¡	fu hao	1000
â†˜	fu hao	1000
â•	fu hao	1000
ğŸˆ¹	fu hao	1000
ğŸ†—	fu hao	1000
â­	fu hao	1000
ğŸ”¯	fu hao	1000
â­•	fu hao	1000
â¤	fu hao	1000
â¬†	fu hao	1000
ğŸˆš	fu hao	1000
ğŸ”	fu hao	1000
â¿	fu hao	1000
ãŠ™	fu hao	1000
â—	fu hao	1000
ğŸ†’	fu hao	1000
Â©	fu hao	1000
Â®	fu hao	1000
ğŸˆ¸	fu hao	1000
âœ³	fu hao	1000
ğŸˆ¯	fu hao	1000
â”	fu hao	1000
ğŸˆ³	fu hao	1000
â„¢	fu hao	1000
â†—	fu hao	1000
ğŸ†š	fu hao	1000
ğŸˆ·	fu hao	1000
âŒ	fu hao	1000
â¬…	fu hao	1000
ğŸ†•	fu hao	1000
â†™	fu hao	1000
ğŸ†™	fu hao	1000
ğŸ”±	fu hao	1000
â¬‡	fu hao	1000
ğŸˆ¶	fu hao	1000
ğŸ†”	fu hao	1000
â“	fu hao	1000
ğŸˆº	fu hao	1000
ğŸ‰	fu hao	1000
â†–	fu hao	1000
ğŸ’	fu wu yuan	1000
ğŸ‘¢	fu zhuang	1000
ğŸ©	fu zhuang	1000
ğŸ‘”	fu zhuang	1000
ğŸ‘—	fu zhuang	1000
ğŸ‘ 	fu zhuang	1000
ğŸ‘’	fu zhuang	1000
ğŸ‘•	fu zhuang	1000
ğŸ‘˜	fu zhuang	1000
ğŸ‘¡	fu zhuang	1000
ğŸ‘™	fu zhuang	1000
ğŸ‘œ	fu zhuang	1000
ğŸ‘Ÿ	fu zhuang	1000
ğŸ‘‘	fu zhuang	1000
ğŸ»	gan bei	1000
ğŸŠ	gan ju	1000
â›³	gao er fu	1000
ğŸ˜Š	gao xing	1000
ğŸ˜ƒ	gao xing	1000
ğŸ˜„	gao xing	1000
ğŸˆ¹	ge	1000
ğŸ­	gong chang	1000
ğŸšŒ	gong gong qi che	1000
âœ‚	gong ju	1000
ğŸ””	gong ju	1000
ğŸ”‘	gong ju	1000
ğŸ”«	gong ju	1000
ğŸ”¨	gong ju	1000
ğŸ”“	gong ju	1000
ğŸ”	gong ju	1000
ğŸ”’	gong ju	1000
â›²	gong yuan	1000
ğŸ‘¸	gong zhu	1000
ğŸ—	gong zhu	1000
ğŸ¶	gou	1000
ğŸ¶	gou lian	1000
ğŸ’©	gou shi	1000
ğŸ‘	gu zhang	1000
ğŸ‘¾	guai shou	1000
ğŸ¢	guan dong zhu	1000
ğŸ“¢	guang bo	1000
ğŸ“€	guang pan	1000
ğŸ’¿	guang pan	1000
ğŸ˜œ	gui lian	1000
ğŸ‘»	gui lian	1000
ğŸ˜„	ha ha	1000
ğŸš	hai bei	1000
ğŸŒŠ	hai lang	1000
ğŸ˜±	hai pa	1000
ğŸ˜¨	hai pa	1000
ğŸ¬	hai tun	1000
ğŸ˜³	hai xiu	1000
ğŸ˜“	han	1000
ğŸ˜°	han	1000
ğŸ’¦	han	1000
ğŸ’¦	han shui	1000
ğŸ‘Œ	hao	1000
ğŸ†—	hao	1000
ğŸ€	hao yun	1000
ğŸ±	he fan	1000
ğŸ‘˜	he fu	1000
ğŸ˜„	he he	1000
â™ 	hei tao	1000
ğŸ’‹	hong chun	1000
ğŸŠ	hong ju	1000
ğŸš¥	hong lv deng	1000
ğŸ	hong ping guo	1000
â™¥	hong tao	1000
ğŸ€„	hong zhong	1000
ğŸ’	hou	1000
ğŸµ	hou lian	1000
ğŸµ	hou zi	1000
ğŸ’	hou zi	1000
ğŸµ	hou zi lian	1000
ğŸ¯	hu lian	1000
ğŸ’	hua shu	1000
ğŸ¿	hua xue	1000
ğŸ‘‘	huang gu an	1000
ğŸ‘‘	huang guan	1000
ğŸŒ†	huang hun	1000
ğŸ’›	huang xin	1000
ğŸ’¦	hui han ru yu	1000
ğŸ‘‹	hui shou	1000
ğŸ”¥	huo	1000
ğŸ’±	huo bi dui huan	1000
ğŸš„	huo che	1000
ğŸšš	huo che	1000
ğŸš…	huo che	1000
ğŸš‰	huo che zhan	1000
ğŸ‰	huo de	1000
â›º	huo dong	1000
ğŸ’…	huo dong	1000
ğŸ›€	huo dong	1000
ğŸ—½	huo dong	1000
ğŸ’‰	huo dong	1000
ğŸ€„	huo dong	1000
â›²	huo dong	1000
ğŸ«	huo dong	1000
ğŸ¤	huo dong	1000
ğŸ¨	huo dong	1000
ğŸ’	huo dong	1000
ğŸ’Š	huo dong	1000
ğŸ¬	huo dong	1000
ğŸ¡	huo dong	1000
ğŸ¥	huo dong	1000
ğŸ¢	huo dong	1000
ğŸ’„	huo dong	1000
ğŸ¦	huo dong	1000
ğŸ’ˆ	huo dong	1000
â›½	huo dong	1000
ğŸš€	huo jian	1000
ğŸ”¥	huo yan	1000
ğŸ”	ji	1000
ğŸ¤	ji bao bao	1000
ğŸš‘	ji jiu che	1000
ğŸ“	ji lu	1000
ğŸ¸	ji ta	1000
ğŸ¸	ji wei jiu	1000
ğŸ‘«	jia ren	1000
ğŸ˜	jia xiao	1000
â›½	jia you	1000
â›½	jia you zhan	1000
ğŸ˜£	jian ren	1000
â†™	jian tou	1000
â†—	jian tou	1000
â†˜	jian tou	1000
â†–	jian tou	1000
â¬†	jian tou	1000
â¬‡	jian tou	1000
â¬…	jian tou	1000
â¡	jian tou	1000
ğŸ¨	jian zhu	1000
â›ª	jian zhu	1000
ğŸ¬	jian zhu	1000
ğŸ¥	jian zhu	1000
ğŸ°	jian zhu	1000
ğŸ©	jian zhu	1000
ğŸ­	jian zhu	1000
ğŸ¢	jian zhu	1000
ğŸ¦	jian zhu	1000
ğŸª	jian zhu	1000
ğŸ£	jian zhu	1000
ğŸ§	jian zhu	1000
ğŸ«	jian zhu	1000
ğŸ 	jian zhu	1000
ğŸ¯	jian zhu	1000
ğŸ‘·	jian zhu gong ren	1000
âœ‚	jian zi	1000
ğŸ†	jiang bei	1000
ğŸ˜°	jiao ji	1000
ğŸ’Š	jiao nang	1000
â›ª	jiao tang	1000
ğŸš²	jiao tong	1000
ğŸš…	jiao tong	1000
ğŸš¤	jiao tong	1000
â›µ	jiao tong	1000
ğŸš§	jiao tong	1000
ğŸš™	jiao tong	1000
ğŸš€	jiao tong	1000
ğŸš‘	jiao tong	1000
ğŸšƒ	jiao tong	1000
ğŸš¢	jiao tong	1000
ğŸš¶	jiao tong	1000
ğŸš¥	jiao tong	1000
ğŸš—	jiao tong	1000
ğŸš‰	jiao tong	1000
ğŸšš	jiao tong	1000
ğŸšŒ	jiao tong	1000
ğŸ’º	jiao tong	1000
âœˆ	jiao tong	1000
ğŸš	jiao tong	1000
ğŸš’	jiao tong	1000
ğŸš„	jiao tong	1000
ğŸš•	jiao tong	1000
ğŸš‡	jiao tong	1000
ğŸš“	jiao tong	1000
ğŸš¥	jiao tong biao zhi	1000
ğŸš§	jiao tong biao zhi	1000
ğŸš„	jiao tong gong ju	1000
ğŸšŒ	jiao tong gong ju	1000
ğŸ‘£	jiao yin	1000
ğŸ”“	jie suo	1000
ğŸ’	jie wen	1000
ğŸ’	jie zhi	1000
ğŸ‘±	jin fa	1000
ğŸ’°	jin qian	1000
ğŸ˜“	jin zhang	1000
ğŸ‘®	jing cha	1000
ğŸš“	jing che	1000
âš 	jing gao	1000
ğŸ³	jing yu	1000
ğŸ˜³	jiong	1000
ğŸ¨	jiu dian	1000
ğŸš‘	jiu hu che	1000
ğŸ™‡	ju gong	1000
ğŸŠ	ju zi	1000
ğŸ’ƒ	jue se	1000
ğŸ˜ 	jue zui	1000
ğŸ˜¡	jue zui	1000
â˜•	ka fei	1000
ğŸ”“	kai suo	1000
ğŸ˜„	kai xin	1000
ğŸ¨	kao la	1000
ğŸ¶	ke ai	1000
ğŸˆ³	kong	1000
ğŸ˜±	kong bu	1000
ğŸ˜·	kou zhao	1000
ğŸ˜­	ku	1000
ğŸ˜¢	ku	1000
ğŸ†’	ku	1000
ğŸ’€	ku lou tou	1000
ğŸ˜­	ku qi	1000
ğŸ˜¢	ku qi	1000
ğŸ’¨	kuai pao	1000
ğŸ˜–	kun huo	1000
ğŸ˜ª	kun juan	1000
ğŸº	la ba	1000
ğŸœ	la mian	1000
ğŸ’©	la shi	1000
ğŸ€	lan qiu	1000
ğŸ’™	lan xin	1000
ğŸº	lang	1000
ğŸ’	lang man	1000
ğŸ’™	lang man	1000
ğŸ’’	lang man	1000
ğŸ’	lang man	1000
ğŸ’‹	lang man	1000
ğŸ’š	lang man	1000
ğŸ’	lang man	1000
ğŸ’“	lang man	1000
ğŸ’—	lang man	1000
ğŸ’›	lang man	1000
ğŸ’	lang man	1000
ğŸ’Ÿ	lang man	1000
ğŸ’”	lang man	1000
ğŸŒ¹	lang man	1000
ğŸ’˜	lang man	1000
ğŸ’	lang man	1000
ğŸ’œ	lang man	1000
ğŸ’‘	lang man	1000
ğŸ‘µ	lao fu ren	1000
ğŸ¯	lao hu	1000
ğŸ°	lao hu ji	1000
ğŸ‘µ	lao nai nai	1000
ğŸ‘´	lao ren	1000
ğŸ­	lao shu	1000
ğŸ‘´	lao ye ye	1000
ğŸ˜“	leng han	1000
ğŸ˜°	leng han	1000
ğŸ’‡	li fa	1000
ğŸ’ˆ	li fa dian	1000
ğŸ‘’	li mao	1000
ğŸ©	li mao	1000
ğŸ	li pin	1000
ğŸ	li wu	1000
ğŸ˜³	lian hong	1000
ğŸ””	ling dang	1000
ğŸ••	liu dian zhong	1000
ğŸ˜¢	liu lei	1000
ğŸ˜­	liu lei	1000
ğŸŒ€	long juan feng	1000
ğŸ 	lou fang	1000
ğŸ“¼	lu xiang dai	1000
â›º	lu ying	1000
ğŸ«	luo tuo	1000
ğŸ‚	luo ye	1000
ğŸµ	lv cha	1000
ğŸ¨	lv gu an	1000
ğŸ¨	lv guan	1000
ğŸ’š	lv xin	1000
ğŸ	ma	1000
ğŸ´	ma	1000
ğŸ€„	ma jiang	1000
ğŸ´	ma lian	1000
ğŸš½	ma tong	1000
â›µ	ma tou	1000
ğŸˆµ	man	1000
ğŸ±	mao	1000
ğŸ±	mao lian	1000
ğŸ›	mao mao chong	1000
ğŸ©	mao zi	1000
ğŸ‘’	mao zi	1000
ğŸŒ¹	mei gui	1000
â™£	mei hua	1000
ğŸ’†	mei rong	1000
ğŸ“º	mei ti	1000
ğŸ“»	mei ti	1000
ğŸš	mi fan	1000
ãŠ™	mi mi	1000
ğŸ	mian bao	1000
ğŸœ	mian tiao	1000
ğŸ‘	mian yang	1000
ğŸ¯	ming zhong	1000
â™‘	mo jie zuo	1000
ğŸ¡	mo tian lun	1000
ğŸ®	mu niu	1000
ğŸƒ	nan gua	1000
ğŸƒ	nan gua deng long	1000
ğŸ‘¦	nan hai	1000
ğŸ‘¨	nan ren	1000
ğŸš¹	nan shi	1000
ğŸ˜ 	nao xin	1000
ğŸ¦	ni ao	1000
ğŸ¦	niao	1000
ğŸ‘§	nv hai	1000
ğŸ‘©	nv ren	1000
ğŸšº	nv shi	1000
ğŸ‰	pai dui	1000
ğŸ‘	pai shou	1000
ğŸƒ	pao bu	1000
ğŸ»	peng bei	1000
ğŸ³	peng ren	1000
ğŸ»	pi jiu	1000
ğŸº	pi jiu	1000
ğŸ˜ª	pi lao	1000
ğŸ«	piao ju	1000
ğŸ	ping guo	1000
ğŸ’°	qi an	1000
ğŸ•–	qi dian zhong	1000
ğŸ§	qi e	1000
ğŸ’¢	qi fen	1000
ğŸ˜¡	qi fen	1000
ğŸ˜ 	qi fen	1000
ğŸ‘ƒ	qi guan	1000
ğŸ‘€	qi guan	1000
ğŸ‘£	qi guan	1000
ğŸ‘‚	qi guan	1000
ğŸ‘„	qi guan	1000
ğŸˆ	qi qiu	1000
ğŸ’°	qian	1000
ğŸ’°	qian dai	1000
ğŸ‘«	qian shou	1000
ğŸ”«	qiang	1000
ğŸ’ª	qiang zhuang	1000
ğŸ§	qie	1000
ğŸ†	qie zi	1000
ğŸ˜˜	qin qin	1000
ğŸ˜š	qin qin	1000
ğŸ˜š	qin wen	1000
ğŸ’	qin wen	1000
ğŸˆ	qing dian	1000
ğŸ‰	qing dian	1000
ğŸ‘«	qing lv	1000
ğŸ’‘	qing lv	1000
â˜€	qing tian	1000
ğŸ¸	qing wa	1000
ğŸ	qing zhu	1000
ğŸ…	qing zhu	1000
ğŸ‰	qing zhu	1000
ğŸ‚	qing zhu	1000
ğŸ†	qing zhu	1000
ğŸ‘	qing zhu	1000
ğŸ	qing zhu	1000
ğŸƒ	qing zhu	1000
ğŸ‡	qing zhu	1000
ğŸ€	qing zhu	1000
ğŸ	qing zhu	1000
ğŸ„	qing zhu	1000
ğŸ“	qing zhu	1000
ğŸˆ	qing zhu	1000
ğŸ	qing zhu	1000
ğŸ‘Š	quan tou	1000
â›½	ran liao	1000
ğŸ 	re dai yu	1000
ğŸ²	re qi teng teng	1000
ğŸŒ…	ri chu	1000
ğŸŒ„	ri chu	1000
ğŸ·	sa ke si	1000
ğŸ	sai che	1000
ğŸ”±	san cha ji	1000
â—€	san jiao	1000
â–¶	san jiao	1000
ğŸš	shan bei	1000
âš¡	shan dian	1000
ğŸ’¼	shang ban	1000
ğŸ‘†	shang mian	1000
â˜	shang wu	1000
ğŸ’±	shang wu	1000
ğŸ“–	shang wu	1000
ğŸ	she	1000
ğŸ¥	she ying ji	1000
ğŸˆ¸	shen	1000
ğŸ†”	shen fen	1000
ğŸˆ¸	shen qing	1000
ğŸ˜·	sheng bing	1000
ğŸ…	sheng dan lao ren	1000
ğŸ„	sheng dan shu	1000
âœŒ	sheng li	1000
ğŸ˜ 	sheng qi	1000
ğŸ˜¡	sheng qi	1000
ğŸ‚	sheng ri	1000
ğŸ‚	sheng ri dan gao	1000
ğŸ”Š	sheng yin	1000
ğŸ”	shi ba jin	1000
ğŸš§	shi gong	1000
ğŸ•—	shi jian	1000
ğŸ•›	shi jian	1000
ğŸ•	shi jian	1000
ğŸ•”	shi jian	1000
ğŸ•˜	shi jian	1000
ğŸ•‘	shi jian	1000
ğŸ••	shi jian	1000
ğŸ•™	shi jian	1000
ğŸ•’	shi jian	1000
ğŸ•–	shi jian	1000
ğŸ•š	shi jian	1000
ğŸ•“	shi jian	1000
ğŸ˜Œ	shi ran	1000
ğŸ˜¥	shi wang	1000
ğŸ˜	shi wang	1000
ğŸ±	shi wu	1000
ğŸ›	shi wu	1000
ğŸŸ	shi wu	1000
ğŸ£	shi wu	1000
ğŸ°	shi wu	1000
ğŸ§	shi wu	1000
ğŸš	shi wu	1000
ğŸ	shi wu	1000
ğŸ´	shi wu	1000
ğŸ¢	shi wu	1000
ğŸ™	shi wu	1000
ğŸ³	shi wu	1000
ğŸ¦	shi wu	1000
ğŸ	shi wu	1000
ğŸ”	shi wu	1000
ğŸ¡	shi wu	1000
ğŸ˜	shi wu	1000
ğŸœ	shi wu	1000
ğŸ²	shi wu	1000
â˜	shi zhi	1000
ğŸ‘‹	shou	1000
ğŸ‘	shou	1000
ğŸ“±	shou ji	1000
ğŸ”«	shou qiang	1000
ğŸ‘	shou shi	1000
ğŸ™	shou shi	1000
ğŸ‘ˆ	shou shi	1000
ğŸ‘Œ	shou shi	1000
ğŸ‘	shou shi	1000
ğŸ™Œ	shou shi	1000
ğŸ‘‰	shou shi	1000
ğŸ‘	shou shi	1000
ğŸ‘†	shou shi	1000
â˜	shou shi	1000
ğŸ‘Š	shou shi	1000
ğŸ‘	shou shi	1000
ğŸ‘‡	shou shi	1000
âœŒ	shou shi	1000
âœŠ	shou shi	1000
âœ‹	shou shi	1000
ğŸ‘‹	shou shi	1000
ğŸ£	shou si	1000
ğŸ‘œ	shou ti bao	1000
ğŸ‰	shou yi	1000
ğŸ“»	shou yin ji	1000
ğŸ’	shu bao	1000
ğŸ¨	shu dai xiong	1000
ğŸ­	shu lian	1000
ğŸ’¤	shu shui	1000
â™“	shuang yu zuo	1000
ğŸ‘	shuang zhang	1000
â™Š	shuang zi zuo	1000
ğŸŒ¾	shui dao	1000
ğŸ“	shui guo	1000
ğŸ…	shui guo	1000
ğŸ‰	shui guo	1000
ğŸ†	shui guo	1000
ğŸŠ	shui guo	1000
ğŸ	shui guo	1000
ğŸ’¤	shui jiao	1000
ğŸ˜ª	shui jiao	1000
ğŸ€	si dai	1000
ğŸ˜”	si kao	1000
ğŸ€	si ye cao	1000
ğŸ”	sou suo	1000
ğŸ”’	suo	1000
ğŸ±	tai qiu	1000
â˜€	tai yang	1000
ğŸœ	tang mian	1000
ğŸ’¨	tao li	1000
ğŸ‰	te jia	1000
ğŸŒ€	tian qi	1000
â›„	tian qi	1000
ğŸŒ‚	tian qi	1000
â˜€	tian qi	1000
â˜”	tian qi	1000
â˜	tian qi	1000
ğŸ‘¼	tian shi	1000
ğŸ‘¼	tian shi bao bao	1000
âœ¨	tian wen	1000
ğŸŒŸ	tian wen	1000
ğŸŒ™	tian wen	1000
ğŸ’ƒ	tiao wu	1000
ğŸ‘¿	tong hua	1000
ğŸ‘¸	tong hua	1000
ğŸ“¡	tong xun	1000
ğŸ’€	tou gu	1000
ğŸ‘¾	tou xiang	1000
ğŸ’	tou xiang	1000
ğŸ™…	tou xiang	1000
ğŸ‘³	tou xiang	1000
ğŸ’‡	tou xiang	1000
ğŸ‘¶	tou xiang	1000
ğŸ‘¨	tou xiang	1000
ğŸ‘¼	tou xiang	1000
ğŸ‘¿	tou xiang	1000
ğŸ‘®	tou xiang	1000
ğŸ’‚	tou xiang	1000
ğŸ‘±	tou xiang	1000
ğŸ™†	tou xiang	1000
ğŸ‘´	tou xiang	1000
ğŸ‘¦	tou xiang	1000
ğŸ‘·	tou xiang	1000
ğŸ‘©	tou xiang	1000
ğŸ‘½	tou xiang	1000
ğŸ’€	tou xiang	1000
ğŸ‘¯	tou xiang	1000
ğŸ‘²	tou xiang	1000
ğŸ’ƒ	tou xiang	1000
ğŸ™‡	tou xiang	1000
ğŸ‘µ	tou xiang	1000
ğŸ’†	tou xiang	1000
ğŸ‘¸	tou xiang	1000
ğŸ‘§	tou xiang	1000
ğŸ‘»	tou xiang	1000
ğŸ°	tu li an	1000
ğŸ‘¯	tu nv lang	1000
ğŸ°	tu zi	1000
ğŸ‘½	wai xing ren	1000
ğŸ¾	wang qiu	1000
ğŸ’‚	wei bing	1000
ğŸš»	wei sheng jian	1000
ğŸ˜ƒ	wei xiao	1000
ğŸ˜„	wei xiao	1000
ğŸ˜	wei xiao	1000
â™¨	wen quan	1000
ğŸˆš	wu	1000
ğŸ˜„	xi ao	1000
ğŸ˜Š	xi ao	1000
ğŸ¤	xi ao ji	1000
ğŸ‘ 	xi e	1000
ğŸ‘Ÿ	xi e	1000
ğŸ‰	xi gua	1000
ğŸ…	xi hong shi	1000
ğŸ˜	xi huan	1000
ğŸ’“	xi huan	1000
ğŸ˜„	xi xi	1000
ğŸ˜	xi xi	1000
ğŸš¬	xi yan	1000
ğŸŒ‡	xi yang	1000
ğŸ›€	xi zao	1000
ğŸ‘‡	xia mian	1000
ğŸŒµ	xian ren zhang	1000
ğŸ˜	xiang	1000
ğŸ’¡	xiang fa	1000
ğŸ“·	xiang ji	1000
ğŸ””	xiang ling	1000
ğŸŒ»	xiang ri kui	1000
ğŸ˜Š	xiao	1000
ğŸ˜„	xiao	1000
ğŸš’	xiao fang che	1000
ğŸ¶	xiao gou	1000
ğŸ¤	xiao ji	1000
ğŸ˜Š	xiao lian	1000
ğŸ˜ƒ	xiao lian	1000
ğŸ¦	xiao niao	1000
ğŸ˜„	xiao yan	1000
ğŸ·	xiao zhu	1000
ğŸ‘ 	xie	1000
ğŸ‘Ÿ	xie	1000
â¤	xin	1000
ğŸ†•	xin	1000
ğŸ’¢	xin qing	1000
ğŸ’¦	xin qing	1000
ğŸ’ª	xin qing	1000
ğŸ’£	xin qing	1000
ğŸ’¤	xin qing	1000
ğŸ’¨	xin qing	1000
ğŸ’©	xin qing	1000
ğŸ’”	xin sui	1000
ğŸ’¼	xin xi	1000
ğŸ“£	xin xi	1000
ğŸ“€	xin xi	1000
ğŸ”Š	xin xi	1000
ğŸ’»	xin xi	1000
ğŸ“´	xin xi	1000
ğŸ“«	xin xi	1000
ğŸ“¢	xin xi	1000
ğŸ’¿	xin xi	1000
ğŸ“¼	xin xi	1000
ğŸ“³	xin xi	1000
ğŸ“	xin xi	1000
ğŸ“·	xin xi	1000
ğŸ“®	xin xi	1000
ğŸ“¡	xin xi	1000
ğŸ“»	xin xi	1000
ğŸ“²	xin xi	1000
ğŸ“©	xin xi	1000
ğŸ“ 	xin xi	1000
ğŸ’½	xin xi	1000
ğŸ“¶	xin xi	1000
ğŸ“º	xin xi	1000
ğŸ“±	xin xi	1000
ğŸ“«	xin xiang	1000
ğŸ’Ÿ	xin xing zhuang shi	1000
ğŸŒ™	xin yue	1000
ğŸŒƒ	xing kong	1000
ğŸš¶	xing ren	1000
ğŸŒŸ	xing xing	1000
âœ¨	xing xing	1000
â›	xing zuo	1000
â™’	xing zuo	1000
â™“	xing zuo	1000
â™	xing zuo	1000
â™‘	xing zuo	1000
â™	xing zuo	1000
â™	xing zuo	1000
â™	xing zuo	1000
â™Œ	xing zuo	1000
â™Š	xing zuo	1000
â™‹	xing zuo	1000
â™ˆ	xing zuo	1000
â™‰	xing zuo	1000
ğŸ»	xiong	1000
ğŸ¦	xue gao	1000
â›„	xue ren	1000
ğŸ«	xue xiao	1000
ğŸ‘€	yan	1000
ğŸ‡	yan hua	1000
ğŸ†	yan hua	1000
ğŸ‡	yan huo	1000
ğŸ†	yan huo	1000
ğŸ‘€	yan jing	1000
ğŸ‘	yang	1000
ğŸ”‘	yao shi	1000
ğŸ’Š	yao wan	1000
â›º	ye ying	1000
ğŸ—	ye zhu	1000
ğŸƒ	ye zi	1000
ğŸ‘”	yi fu	1000
ğŸ‘—	yi fu	1000
ğŸ’˜	yi jian zhong qing	1000
ğŸ’‰	yi liao	1000
ğŸ’Š	yi liao	1000
ğŸˆµ	yi man	1000
ğŸ˜–	yi wen	1000
ğŸ¥	yi yuan	1000
ğŸ¶	yin fu	1000
ğŸµ	yin fu	1000
ğŸ¦	yin hang	1000
ğŸ¸	yin yue	1000
ğŸµ	yin yue	1000
ğŸº	yin yue	1000
ğŸ·	yin yue	1000
ğŸ¶	yin yue	1000
ğŸ§	yin yue	1000
ğŸ¤	yin yue	1000
ğŸˆº	ying	1000
ğŸš¼	ying er	1000
ğŸ‘¶	ying er	1000
ğŸŒ¸	ying hua	1000
ğŸˆ¶	you	1000
ğŸ‘‰	you bian	1000
ğŸšƒ	you gui dian che	1000
ğŸ£	you ju	1000
ğŸ‘»	you ling	1000
ğŸ“®	you tong	1000
ğŸ°	you xi	1000
ğŸ“®	you xiang	1000
ğŸŠ	you yong	1000
ğŸ 	yu	1000
ğŸŸ	yu	1000
ğŸˆ¯	yu ding	1000
ğŸˆ·	yu e	1000
ğŸŒ·	yu jin xiang	1000
ğŸ¤	yu le	1000
ğŸ¢	yu le	1000
â˜”	yu san	1000
ğŸŒ‚	yu san	1000
â­•	yuan quan	1000
ğŸˆ·	yue	1000
ğŸŒ™	yue liang	1000
ğŸ†	yun dong	1000
ğŸŠ	yun dong	1000
ğŸ¿	yun dong	1000
ğŸƒ	yun dong	1000
ğŸ€	yun dong	1000
ğŸ„	yun dong	1000
ğŸˆ	yun dong	1000
ğŸ	yun dong	1000
â›³	yun dong	1000
âš½	yun dong	1000
âš¾	yun dong	1000
ğŸ¾	yun dong	1000
ğŸ‘‹	zai jian	1000
ğŸ‘	zan	1000
ğŸ’£	zha dan	1000
ğŸ˜œ	zha yan	1000
ğŸ˜‰	zha yan	1000
â›º	zhang peng	1000
ğŸ‘	zhang sheng	1000
ğŸ™	zhang yu	1000
ğŸ“·	zhao xiang ji	1000
ğŸœ	zheng wan	1000
ğŸ’…	zhi jia you	1000
ğŸŒ´	zhi wu	1000
ğŸ	zhi wu	1000
ğŸŒ¸	zhi wu	1000 
ğŸ€	zhi wu	1000
ğŸŒ·	zhi wu	1000
ğŸŒ»	zhi wu	1000
ğŸƒ	zhi wu	1000
ğŸ	zhi wu	1000
ğŸŒº	zhi wu	1000
ğŸŒ¾	zhi wu	1000
ğŸ‚	zhi wu	1000
ğŸŒµ	zhi wu	1000
ğŸŒ¹	zhi wu	1000
ğŸ	zhong dian	1000
â˜”	zhou yu	1000
ğŸ—	zhu	1000
ğŸ·	zhu li an	1000
ğŸ·	zhu lian	1000
ğŸ’‰	zhu she qi	1000
ğŸ·	zhu tou	1000
ğŸ 	zhu zhai lou	1000
ğŸ±	zhuo qiu	1000
ğŸŒ‡	zi ran	1000
ğŸŒ†	zi ran	1000
ğŸŒŠ	zi ran	1000
ğŸŒ…	zi ran	1000
ğŸŒ„	zi ran	1000
ğŸŒˆ	zi ran	1000
ğŸŒƒ	zi ran	1000
ğŸ’œ	zi xin	1000
ğŸš²	zi xing che	1000
ğŸ—½	zi you nv shen	1000
ğŸ‘£	zu ji	1000
âš½	zu qiu	1000
ğŸ’	zuan shi	1000
ğŸ‘„	zui	1000
ğŸ‘„	zui ba	1000
ğŸ‘ˆ	zuo bian	1000
ğŸ’º	zuo wei	1000
